Repository EOSIO/eos, pull requests merged in 2018-04, with the labels that each got.

#1969 Feature/stricter auth checks
  contracts/asserter/asserter.cpp
  contracts/eosio.bios/eosio.bios.hpp
  contracts/eosiolib/currency.hpp
  contracts/multi_index_test/multi_index_test.cpp
  contracts/proxy/proxy.cpp
  contracts/test_api/test_action.cpp
  contracts/test_api/test_api.cpp
  contracts/test_api/test_api.hpp
  contracts/test_api/test_transaction.cpp
  contracts/test_api_db/test_api_db.cpp
  contracts/test_api_mem/test_api_mem.cpp
  contracts/test_api_multi_index/test_api_multi_index.cpp
  libraries/chain/apply_context.cpp
  libraries/chain/chain_controller.cpp
  libraries/chain/contracts/chain_initializer.cpp
  libraries/chain/contracts/eosio_contract.cpp
  libraries/chain/include/eosio/chain/apply_context.hpp
  libraries/chain/include/eosio/chain/contracts/eos_contract.hpp
  libraries/chain/include/eosio/chain/exceptions.hpp
  libraries/chain/include/eosio/chain/transaction_metadata.hpp
  libraries/chain/include/eosio/chain/transaction_trace.hpp
  libraries/chain/transaction_metadata.cpp
  libraries/chain/wasm_interface.cpp
  tests/api_tests/api_tests.cpp
  tests/chain_tests/auth_tests.cpp
  tests/chain_tests/block_tests.cpp
  tests/chain_tests/delay_tests.cpp
  tests/wasm_tests/currency_tests.cpp
  tests/wasm_tests/eosio.system_tests.cpp
  tests/wasm_tests/exchange_tests.cpp
  tests/wasm_tests/identity_tests.cpp
  tests/wasm_tests/test_softfloat_wasts.hpp
  tests/wasm_tests/test_wasts.hpp
  tests/wasm_tests/wasm_tests.cpp
Labels: Needs Revisions, invalid

#1600 DAWN-386 fix some of the test cases in special_accounts_tests
  tests/CMakeLists.txt
  tests/tests/special_accounts_tests.cpp
Labels: needs review

#2104 Change block id
  libraries/chain/block.cpp
  tests/chain_tests/block_tests.cpp
Labels: code review

#2348 p2p memory leak fix
  plugins/net_plugin/net_plugin.cpp
Labels: needs review
