Repository EOSIO/eos, pull requests merged in 2018-05, with the labels that each got.

#2777 net and cpu window size parameters
  libraries/chain/include/eosio/chain/resource_limits_private.hpp
  libraries/chain/resource_limits.cpp
Labels: needs testing - fail

#2896 in-flight PR feedback from 2853
  libraries/chain/apply_context.cpp
  libraries/chain/controller.cpp
  tests/testUtils.py
Labels: in progress

#3342 Set Chain ID from CMake
  libraries/chain/CMakeLists.txt
  libraries/chain/chain_id.cpp.in
  libraries/chain/genesis_state.cpp
  libraries/chain/include/eosio/chain/config.hpp
  libraries/chain/include/eosio/chain/genesis_state.hpp
  libraries/chain/include/eosio/chain/types.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/net_plugin/net_plugin.cpp
Labels: Needs Revisions

#3465 Contract Fuzz Testing Fixes
  libraries/wasm-jit/Source/IR/Validate.cpp
  libraries/wasm-jit/Source/Runtime/LLVMJIT.cpp
  libraries/wasm-jit/Source/WASM/WASMSerialization.cpp
  unittests/contracts/fuzz1.wasm
  unittests/contracts/fuzz10.wasm
  unittests/contracts/fuzz11.wasm
  unittests/contracts/fuzz12.wasm
  unittests/contracts/fuzz2.wasm
  unittests/contracts/fuzz3.wasm
  unittests/contracts/fuzz4.wasm
  unittests/contracts/fuzz5.wasm
  unittests/contracts/fuzz6.wasm
  unittests/contracts/fuzz7.wasm
  unittests/contracts/fuzz8.wasm
  unittests/contracts/fuzz9.wasm
  unittests/incbin.h
  unittests/wasm_tests.cpp
Labels: in progress

#3692 remove private data from deprecation log message
  plugins/producer_plugin/producer_plugin.cpp
Labels: SECURITY
