Repository EOSIO/eos, pull requests merged in 2018-03, with the labels that each got.

#1599 DAWN-638 - Add producer schedule test
  tests/chain_tests/producer_schedule_tests.cpp
Labels: needs review

#1743 Dawn 686 - Pass receiver to apply
  contracts/asserter/asserter.cpp
  contracts/bancor/bancor.cpp
  contracts/currency/currency.cpp
  contracts/eosio.system/delegate_bandwidth.hpp
  contracts/eosio.system/eosio.system.cpp
  contracts/eosio.system/eosio.system.hpp
  contracts/eosiolib/action.h
  contracts/eosiolib/currency.hpp
  contracts/eosiolib/dispatcher.hpp
  contracts/exchange/exchange.cpp
  contracts/identity/identity.cpp
  contracts/identity/identity.hpp
  contracts/identity/test/identity_test.cpp
  contracts/infinite/infinite.cpp
  contracts/multi_index_test/multi_index_test.cpp
  contracts/noop/noop.cpp
  contracts/proxy/proxy.cpp
  contracts/skeleton/skeleton.cpp
  contracts/stltest/stltest.cpp
  contracts/test_api/test_action.cpp
  contracts/test_api/test_api.cpp
  contracts/test_api/test_api.hpp
  contracts/test_api_db/test_api_db.cpp
  contracts/test_api_db/test_db.cpp
  contracts/test_api_mem/test_api_mem.cpp
  contracts/test_api_multi_index/test_api_multi_index.cpp
  contracts/test_api_multi_index/test_multi_index.cpp
  contracts/tic_tac_toe/tic_tac_toe.cpp
  libraries/chain/wasm_eosio_validation.cpp
  libraries/chain/wasm_interface.cpp
  libraries/chain/wast_to_wasm.cpp
  libraries/chain/webassembly/binaryen.cpp
  libraries/chain/webassembly/wavm.cpp
  tests/api_tests/api_tests.cpp
  tests/wasm_tests/test_softfloat_wasts.hpp
  tests/wasm_tests/test_wasts.hpp
  tests/wasm_tests/wasm_tests.cpp
Labels: HARDFORK

#1859 Delayed Transactions
  libraries/chain/apply_context.cpp
  libraries/chain/chain_controller.cpp
  libraries/chain/contracts/chain_initializer.cpp
  libraries/chain/contracts/eosio_contract.cpp
  libraries/chain/include/eosio/chain/apply_context.hpp
  libraries/chain/include/eosio/chain/authority_checker.hpp
  libraries/chain/include/eosio/chain/chain_controller.hpp
  libraries/chain/include/eosio/chain/contracts/eos_contract.hpp
  libraries/chain/include/eosio/chain/contracts/types.hpp
  libraries/chain/include/eosio/chain/permission_object.hpp
  libraries/chain/include/eosio/chain/transaction.hpp
  libraries/fc/include/fc/time.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/net_plugin/net_plugin.cpp
  tests/chain_tests/block_tests.cpp
  tests/chain_tests/delay_tests.cpp
  tests/tests/abi_tests.cpp
  tests/tests/misc_tests.cpp
Labels: in progress, needs review

#1538 Improve eosioc error message for get, set, wallet, push subcommand
  libraries/chain/chain_controller.cpp
  libraries/chain/contracts/abi_serializer.cpp
  libraries/chain/contracts/eosio_contract.cpp
  libraries/chain/include/eosio/chain/contracts/abi_serializer.hpp
  libraries/chain/include/eosio/chain/exceptions.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/utilities/include/eosio/utilities/exception_macros.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
  plugins/wallet_plugin/wallet.cpp
  plugins/wallet_plugin/wallet_manager.cpp
  programs/cleos/help_text.cpp
  programs/cleos/httpc.cpp
  programs/cleos/main.cpp
  tests/api_tests/api_tests.cpp
  tests/wasm_tests/currency_tests.cpp
  tests/wasm_tests/wasm_tests.cpp
Labels: needs testing

#1979 enforce resource limits
  contracts/eosio.system/common.hpp
  contracts/eosio.system/delegate_bandwidth.hpp
  contracts/eosio.system/eosio.system.abi
  contracts/eosio.system/voting.hpp
  contracts/eosiolib/privileged.hpp
  contracts/eosiolib/transaction.h
  contracts/eosiolib/transaction.hpp
  contracts/proxy/proxy.cpp
  contracts/test_api/test_transaction.cpp
  libraries/chain/CMakeLists.txt
  libraries/chain/apply_context.cpp
  libraries/chain/block.cpp
  libraries/chain/block_trace.cpp
  libraries/chain/chain_controller.cpp
  libraries/chain/contracts/abi_serializer.cpp
  libraries/chain/contracts/chain_initializer.cpp
  libraries/chain/contracts/eosio_contract.cpp
  libraries/chain/global_property_object.cpp
  libraries/chain/include/eosio/chain/apply_context.hpp
  libraries/chain/include/eosio/chain/authority.hpp
  libraries/chain/include/eosio/chain/block.hpp
  libraries/chain/include/eosio/chain/block_trace.hpp
  libraries/chain/include/eosio/chain/chain_config.hpp
  libraries/chain/include/eosio/chain/chain_controller.hpp
  libraries/chain/include/eosio/chain/config.hpp
  libraries/chain/include/eosio/chain/contracts/abi_serializer.hpp
  libraries/chain/include/eosio/chain/contracts/contract_table_objects.hpp
  libraries/chain/include/eosio/chain/contracts/genesis_state.hpp
  libraries/chain/include/eosio/chain/exceptions.hpp
  libraries/chain/include/eosio/chain/generated_transaction_object.hpp
  libraries/chain/include/eosio/chain/global_property_object.hpp
  libraries/chain/include/eosio/chain/rate_limiting.hpp
  libraries/chain/include/eosio/chain/resource_limits.hpp
  libraries/chain/include/eosio/chain/resource_limits_private.hpp
  libraries/chain/include/eosio/chain/transaction.hpp
  libraries/chain/include/eosio/chain/transaction_trace.hpp
  libraries/chain/include/eosio/chain/types.hpp
  libraries/chain/rate_limiting.cpp
  libraries/chain/resource_limits.cpp
  libraries/chain/wasm_interface.cpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  programs/cleos/main.cpp
  tests/CMakeLists.txt
  tests/api_tests/api_tests.cpp
  tests/chain_tests/block_tests.cpp
  tests/chain_tests/delay_tests.cpp
  tests/chain_tests/recovery_tests.cpp
  tests/include/eosio/chain/test/chainbase_fixture.hpp
  tests/library_tests/chain/resource_limits_test.cpp
  tests/tests/abi_tests.cpp
  tests/tests/misc_tests.cpp
  tests/wasm_tests/currency_tests.cpp
  tests/wasm_tests/eosio.system_tests.cpp
  tests/wasm_tests/exchange_tests.cpp
  tests/wasm_tests/multi_index_tests.cpp
  tests/wasm_tests/wasm_tests.cpp
Labels: needs review

#1574 Add permission api
  contracts/eosiolib/datastream.hpp
  contracts/eosiolib/permission.h
  contracts/test_api/test_api.cpp
  contracts/test_api/test_api.hpp
  contracts/test_api/test_permission.cpp
  libraries/chain/chain_controller.cpp
  libraries/chain/include/eosio/chain/chain_controller.hpp
  libraries/chain/wasm_interface.cpp
  tests/api_tests/api_tests.cpp
Labels: HARDFORK
