Repository EOSIO/eos, pull requests merged in 2018-06, with the labels that each got.

#3511 FIX Pass string with whitespaces to cleos in cleos.sh
  CMakeLists.txt
  Docker/cleos.sh
  contracts/eosio.system/eosio.system-bidname-rc.md
  contracts/eosio.system/eosio.system-buyram-rc.md
  contracts/eosio.system/eosio.system-buyrambytes-rc.md
  contracts/eosio.system/eosio.system-canceldelay-rc.md
  contracts/eosio.system/eosio.system-claimrewards-rc.md
  contracts/eosio.system/eosio.system-clause-constitution-rc.md
  contracts/eosio.system/eosio.system-delband-rc.md
  contracts/eosio.system/eosio.system-delegatebw-rc.md
  contracts/eosio.system/eosio.system-deleteauth-rc.md
  contracts/eosio.system/eosio.system-global-rc.md
  contracts/eosio.system/eosio.system-linkauth-rc.md
  contracts/eosio.system/eosio.system-newaccount-rc.md
  contracts/eosio.system/eosio.system-onerror-rc.md
  contracts/eosio.system/eosio.system-producers-rc.md
  contracts/eosio.system/eosio.system-rammarket-rc.md
  contracts/eosio.system/eosio.system-rc.md
  contracts/eosio.system/eosio.system-refund-rc.md
  contracts/eosio.system/eosio.system-refunds-rc.md
  contracts/eosio.system/eosio.system-regproducer-rc.md
  contracts/eosio.system/eosio.system-regproxy-rc.md
  contracts/eosio.system/eosio.system-reqauth-rc.md
  contracts/eosio.system/eosio.system-rmvproducer-rc.md
  contracts/eosio.system/eosio.system-sellram-rc.md
  contracts/eosio.system/eosio.system-setabi-rc.md
  contracts/eosio.system/eosio.system-setalimits-rc.md
  contracts/eosio.system/eosio.system-setcode-rc.md
  contracts/eosio.system/eosio.system-setglimits-rc.md
  contracts/eosio.system/eosio.system-setparams-rc.md
  contracts/eosio.system/eosio.system-setpriv-rc.md
  contracts/eosio.system/eosio.system-setprods-rc.md
  contracts/eosio.system/eosio.system-setram-rc.md
  contracts/eosio.system/eosio.system-undelegatebw-rc.md
  contracts/eosio.system/eosio.system-unlinkauth-rc.md
  contracts/eosio.system/eosio.system-unregprod-rc.md
  contracts/eosio.system/eosio.system-updateauth-rc.md
  contracts/eosio.system/eosio.system-userres-rc.md
  contracts/eosio.system/eosio.system-voteproducer-rc.md
  contracts/eosio.system/eosio.system-voters-rc.md
  contracts/eosio.token/eosio.token-transfer-rc.md
  governance/constitution.md
Labels: invalid

#3949 Fix for large local sets in wasm
  libraries/wasm-jit/Source/WASM/WASMSerialization.cpp
Labels: CONSENSUS, bug

#3961 fix soft_fail billing bug
  libraries/chain/controller.cpp
Labels: CONSENSUS, bug

#4109 Fix issue #4051
  contracts/eosio.system/delegate_bandwidth.cpp
  unittests/eosio.system_tests.cpp
  unittests/ram_tests.cpp
Labels: eosio.system

#4140 Minor cleanup of system contract
  contracts/eosio.system/delegate_bandwidth.cpp
  contracts/eosio.system/eosio.system.abi
  contracts/eosio.system/eosio.system.hpp
  unittests/eosio_system_tester.hpp
Labels: eosio.system

#4158 only thow unexpected fails in apply_block
  libraries/chain/controller.cpp
Labels: CONSENSUS, bug
